spring:
  main:
    allow-bean-definition-overriding: true
    web-application-type: reactive

  data:
    mongodb:
      uri: mongodb://root:bangezez@223.130.152.12:27017/mongo_db?authSource=admin&retryWrites=true&w=majority
  sql:
    init:
      mode: always
      encoding: UTF-8

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type: trace
jwt:
  secret: kjhjmtkjhjmtkjhjmtkjhjmtkjhjmtkjhjmtkjhjmtkjhjmtkjhjmt
  expiration:
    access: 600000
    refresh: 1200000

server:
  port : 8084 #0 으로 하면 비어있는 포트 자동으로 잡음.

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/