spring:
  main:
    allow-bean-definition-overriding: true
    web-application-type: reactive

  data:
    mongodb:
      uri: mongodb://root:bangezez@223.130.152.12:27017/mongo_db?authSource=admin&retryWrites=true&w=majority
  sql:
    init:
      mode: always
      encoding: UTF-8

#  kafka:
#    bootstrap-servers: localhost:9092
#    consumer:
#      group-id: group_id

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type: trace
server:
  port : 8085

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/

# actuator 설정
management:
  endpoints:
    web:
      exposure:
        include: refresh
  endpoint:
    shutdown:
      enabled: true

encrypt:
  key: my-secret

# config 서버는 기본적으로 8888번 포트를 사용
# 그 외에 설정 파일이 있는 위치와 디렉토리 매칭
# uri: 설정파일이 있는 깃 주소
# default-label: 깃 주소의 브랜치 이름
# search-paths: 설정 파일들을 찾을 경로
