server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://223.130.152.12:3306/bangez_db #?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: bangezez
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
      platform: mysql
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc:
          lob:
            '[non_contextual_creation]': true
        '[format_sql]': true
    show-sql: true
    open-in-view: false

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/

imp:
  code: imp05080136
  api:
    key: 7823574325050846
    secretKey: show19RFlbVGhUDoGOKYb8WbrpoEnJaYFaKwGR4kx4IuOuLIAohAwG34Vurk4Yfxcb69jB3MeevMR95R

# actuator 설정
management:
  endpoints:
    web:
      exposure:
        include: refresh
  endpoint:
    shutdown:
      enabled: true

encrypt:
  key: my-secret

# config 서버는 기본적으로 8888번 포트를 사용
# 그 외에 설정 파일이 있는 위치와 디렉토리 매칭
# uri: 설정파일이 있는 깃 주소
# default-label: 깃 주소의 브랜치 이름
# search-paths: 설정 파일들을 찾을 경로
