spring:
  datasource:
    url: jdbc:mysql://223.130.152.12:3306/bangez_db
    username: root
    password: bangezez
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      platform: mysql
      mode: always
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc:
          lob:
            '[non_contextual_creation]': true
        '[format_sql]': true
    show-sql: true
    defer-datasource-initialization : true
    # open-in-view : false
logging:
  level:
    org:
      hibernate:
        SQL: debug
        type: trace
      springframework:
        security: DEBUG
        web: DEBUG
        data: DEBUG
        hibernate: DEBUG
        jpa: DEBUG
        sql: DEBUG
        jwt: DEBUG

server:
  port: 8082

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: refresh
  endpoint:
    shutdown:
      enabled: true

encrypt:
  key: my-secret