apiVersion: v1
kind: Service
metadata:
  name: bangez-service
  labels:
    app: bangez-service
spec:
  type: LoadBalancer
  ports:
    - name: gateway-server
      protocol: TCP
      port: 8000
      targetPort: 8000

    - name: eureka-server
      protocol: TCP
      port: 8761
      targetPort: 8761

    - name: tx-service
      protocol: TCP
      port: 8081
      targetPort: 8081

    - name: user-service
      protocol: TCP
      port: 8082
      targetPort: 8082

    - name: land-service
      protocol: TCP
      port: 8083
      targetPort: 8083

    - name: analysis-service
      protocol: TCP
      port: 8084
      targetPort: 8084

    - name: chat-service
      protocol: TCP
      port: 8085
      targetPort: 8085

  selector:
    app: bangez