apiVersion: apps/v1
kind: Deployment
metadata:
  name: analysis-deployment
  labels:
    app: analysis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analysis
  template:
    metadata:
      labels:
        app: analysis
    spec:
      containers:
        - name: analysis
          image: hyunji0221/analysis:latest
          ports:
            - containerPort: 8084