apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-deployment
  labels:
    app: eureka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka
  template:
    metadata:
      labels:
        app: eureka
    spec:
      containers:
        - name: eureka
          image: hyunji0221/eureka:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8761
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: hyunji0221/gateway:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 443
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tx-deployment
  labels:
    app: tx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tx
  template:
    metadata:
      labels:
        app: tx
    spec:
      containers:
        - name: tx
          image: hyunji0221/tx:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
  labels:
    app: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: hyunji0221/user:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: land-deployment
  labels:
    app: land
spec:
  replicas: 1
  selector:
    matchLabels:
      app: land
  template:
    metadata:
      labels:
        app: land
    spec:
      containers:
        - name: land
          image: hyunji0221/land:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8083
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: analysis-deployment
  labels:
    app: analysis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analysis
  template:
    metadata:
      labels:
        app: analysis
    spec:
      containers:
        - name: analysis
          image: hyunji0221/analysis:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8084
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-deployment
  labels:
    app: chat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat
  template:
    metadata:
      labels:
        app: chat
    spec:
      containers:
        - name: chat
          image: hyunji0221/chat:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8085