apiVersion: apps/v1
kind: Deployment
metadata:
  name: bangez-deployment
  labels:
    app: bangez
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bangez
  template:
    metadata:
      labels:
        app: bangez
    spec:
      containers:
        - name: bangez-eureka
          image: hyunji0221/bangez-eureka:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8761
              
        - name: bangez-gateway
          image: hyunji0221/bangez-gateway:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
              
        - name: bangez-tx
          image: hyunji0221/bangez-tx:latest
          ports:
            - containerPort: 8081
              
        - name: bangez-user
          image: hyunji0221/bangez-user:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
              
        - name: bangez-land
          image: hyunji0221/bangez-land:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8083
              
        - name: bangez-analysis
          image: hyunji0221/bangez-analysis:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8084
              
        - name: bangez-chat
          image: hyunji0221/bangez-chat:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8085