apiVersion: v1
kind: Service
metadata:
  name: eureka-server
  labels:
    app: eureka
spec:
  type: LoadBalancer
  ports:
    - name: eureka
      protocol: TCP
      port: 8761
      targetPort: 8761
  selector:
    app: eureka
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-server
  labels:
    app: gateway
spec:
  type: LoadBalancer
  ports:
    - name: gateway
      protocol: TCP
      port: 443
      targetPort: 443
  selector:
    app: gateway
---
apiVersion: v1
kind: Service
metadata:
  name: tx-service
  labels:
    app: tx
spec:
  type: ClusterIP
  ports:
    - name: tx
      protocol: TCP
      port: 8081
      targetPort: 8081
  selector:
    app: tx
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  labels:
    app: user
spec:
  type: ClusterIP
  ports:
    - name: user
      protocol: TCP
      port: 8082
      targetPort: 8082
  selector:
    app: user
---
apiVersion: v1
kind: Service
metadata:
  name: land-service
  labels:
    app: land
spec:
  type: ClusterIP
  ports:
    - name: land
      protocol: TCP
      port: 8083
      targetPort: 8083
  selector:
    app: land
---
apiVersion: v1
kind: Service
metadata:
  name: analysis-service
  labels:
    app: analysis
spec:
  type: ClusterIP
  ports:
    - name: analysis
      protocol: TCP
      port: 8084
      targetPort: 8084
  selector:
    app: analysis
---
apiVersion: v1
kind: Service
metadata:
  name: chat-service
  labels:
    app: chat
spec:
  type: ClusterIP
  ports:
    - name: chat
      protocol: TCP
      port: 8085
      targetPort: 8085
  selector:
    app: chat
---